# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seats.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bseats.proto\x12\x19sdv.edge.comfort.seats.v1\"<\n\x0bMoveRequest\x12-\n\x04seat\x18\x01 \x01(\x0b\x32\x1f.sdv.edge.comfort.seats.v1.Seat\"\x0b\n\tMoveReply\"\x9c\x01\n\x14MoveComponentRequest\x12\x35\n\x04seat\x18\x01 \x01(\x0b\x32\'.sdv.edge.comfort.seats.v1.SeatLocation\x12;\n\tcomponent\x18\x02 \x01(\x0e\x32(.sdv.edge.comfort.seats.v1.SeatComponent\x12\x10\n\x08position\x18\x03 \x01(\x05\"\x14\n\x12MoveComponentReply\"4\n\x16\x43urrentPositionRequest\x12\x0b\n\x03row\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\r\"E\n\x14\x43urrentPositionReply\x12-\n\x04seat\x18\x01 \x01(\x0b\x32\x1f.sdv.edge.comfort.seats.v1.Seat\"x\n\x04Seat\x12\x39\n\x08location\x18\x01 \x01(\x0b\x32\'.sdv.edge.comfort.seats.v1.SeatLocation\x12\x35\n\x08position\x18\x02 \x01(\x0b\x32#.sdv.edge.comfort.seats.v1.Position\"*\n\x0cSeatLocation\x12\x0b\n\x03row\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\r\"g\n\x08Position\x12\x0c\n\x04\x62\x61se\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ushion\x18\x02 \x01(\x05\x12\x0e\n\x06lumbar\x18\x03 \x01(\x05\x12\x14\n\x0cside_bolster\x18\x04 \x01(\x05\x12\x16\n\x0ehead_restraint\x18\x05 \x01(\x05*X\n\rSeatComponent\x12\x08\n\x04\x42\x41SE\x10\x00\x12\x0b\n\x07\x43USHION\x10\x01\x12\n\n\x06LUMBAR\x10\x02\x12\x10\n\x0cSIDE_BOLSTER\x10\x03\x12\x12\n\x0eHEAD_RESTRAINT\x10\x04\x32\xc5\x02\n\x05Seats\x12T\n\x04Move\x12&.sdv.edge.comfort.seats.v1.MoveRequest\x1a$.sdv.edge.comfort.seats.v1.MoveReply\x12o\n\rMoveComponent\x12/.sdv.edge.comfort.seats.v1.MoveComponentRequest\x1a-.sdv.edge.comfort.seats.v1.MoveComponentReply\x12u\n\x0f\x43urrentPosition\x12\x31.sdv.edge.comfort.seats.v1.CurrentPositionRequest\x1a/.sdv.edge.comfort.seats.v1.CurrentPositionReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seats_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SEATCOMPONENT']._serialized_start=694
  _globals['_SEATCOMPONENT']._serialized_end=782
  _globals['_MOVEREQUEST']._serialized_start=42
  _globals['_MOVEREQUEST']._serialized_end=102
  _globals['_MOVEREPLY']._serialized_start=104
  _globals['_MOVEREPLY']._serialized_end=115
  _globals['_MOVECOMPONENTREQUEST']._serialized_start=118
  _globals['_MOVECOMPONENTREQUEST']._serialized_end=274
  _globals['_MOVECOMPONENTREPLY']._serialized_start=276
  _globals['_MOVECOMPONENTREPLY']._serialized_end=296
  _globals['_CURRENTPOSITIONREQUEST']._serialized_start=298
  _globals['_CURRENTPOSITIONREQUEST']._serialized_end=350
  _globals['_CURRENTPOSITIONREPLY']._serialized_start=352
  _globals['_CURRENTPOSITIONREPLY']._serialized_end=421
  _globals['_SEAT']._serialized_start=423
  _globals['_SEAT']._serialized_end=543
  _globals['_SEATLOCATION']._serialized_start=545
  _globals['_SEATLOCATION']._serialized_end=587
  _globals['_POSITION']._serialized_start=589
  _globals['_POSITION']._serialized_end=692
  _globals['_SEATS']._serialized_start=785
  _globals['_SEATS']._serialized_end=1110
# @@protoc_insertion_point(module_scope)
